"""add importance

Revision ID: 050c58e36424
Revises: 58deb18f3d36
Create Date: 2023-04-08 16:55:29.954221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050c58e36424'
down_revision = '58deb18f3d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('importance', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.drop_column('importance')

    # ### end Alembic commands ###
