"""add is_archive

Revision ID: 58deb18f3d36
Revises: 3b5352adc6a8
Create Date: 2023-04-01 19:57:09.931456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58deb18f3d36'
down_revision = '3b5352adc6a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_archive', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_model', schema=None) as batch_op:
        batch_op.drop_column('is_archive')

    # ### end Alembic commands ###
